jit_model_path: './src/silero_vad/data/silero_vad.jit'  
use_torchhub: True  

tune_8k: False  
train_dataset_path: './datasets/vad_1/train.feather'  
val_dataset_path: './datasets/vad_1/test.feather'  
model_save_path: 'model_save_path.onnx'
onnx_opset_version: 16  

noise_loss: 0.5  
max_train_length_sec: 8  
aug_prob: 0.4  

learning_rate: 5e-4  
batch_size: 64  
num_workers: 8  
num_epochs: 20  
device: 'cuda'  

logdir_tensorboard: '/content/runs/tuning'
checkpoint_save_path: '/content/checkpoints/best_checkpoint.pth'
